---
- name: Set up Herd backend and management
  hosts: backend
  gather_facts: false

  tasks:
    - name: Install apt dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          - pipx
          - git
          - golang-go
          - build-essential
          - nodejs
          - npm
        state: present
        update_cache: yes
      become: true

    - name: Remove old backend repo if it exists
      ansible.builtin.file:
        path: ~/backend
        state: absent

    - name: Remove old endpoint repo if it exists
      ansible.builtin.file:
        path: ~/endpoint
        state: absent

    - name: Remove old management repo if it exists
      ansible.builtin.file:
        path: ~/management
        state: absent

    - name: Clone backend repo
      ansible.builtin.git:
        repo: https://github.com/capybarastone/backend.git
        dest: ~/backend

    - name: Clone endpoint repo
      ansible.builtin.git:
        repo: https://github.com/capybarastone/endpoint.git
        dest: ~/endpoint

    - name: Clone management repo
      ansible.builtin.git:
        repo: https://github.com/capybarastone/management.git
        dest: ~/management

    - name: Sync pip dependencies with UV
      ansible.builtin.shell: |
        cd ~
        pipx install uv
        cd ~/backend
        ~/.local/bin/uv sync

    - name: Set file permissions for backend executable
      ansible.builtin.file:
        path: /home/deployment/backend/run.sh
        mode: '0775'

#    - name: Set perms for data direcotry
#      ansible.builtin.file:
#        path: /home/deployment/backend/data
#        state: directory
#        owner: deployment
#        group: deployment

    - name: Configure systemd service for Herd-backend
      ansible.builtin.copy:
        dest: /etc/systemd/system/herd-backend.service
        content: |
          [Unit]
          Description=Herd Backend Service
          After=network.target
          StartLimitIntervalSec=0
          
          [Service]
          Type=simple
          Restart=always
          RestartSec=1
          User=deployment
          WorkingDirectory=/home/deployment/backend
          ExecStart=/home/deployment/backend/run.sh

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Reload daemon start and enable Herd-backend
      ansible.builtin.systemd_service:
        name: herd-backend.service
        enabled: true
        state: restarted
        daemon_reload: true
      become: true
    

    - name: Build management
      ansible.builtin.shell: |
        cd /home/deployment/management
        npm ci

    - name: make env file
      ansible.builtin.shell: |
        cp "/home/deployment/management/.env.example" "/home/deployment/management/.env"

    - name: update env file
      ansible.builtin.lineinfile:
        path: /home/deployment/management/.env
        regexp: '^BACKEND_CERTS_DIR.*'
        line: 'BACKEND_CERTS_DIR=/home/deployment/backend/certs'
        state: present

    - name: update env file
      ansible.builtin.lineinfile:
        path: /home/deployment/management/.env
        regexp: '^MANAGEMENT_DATA_DIR.*'
        line: 'MANAGEMENT_DATA_DIR=/home/deployment/management/data'
        state: present

    - name: Set file permissions for backend executable
      ansible.builtin.file:
        path: /home/deployment/management/run.sh
        mode: '0775'

    - name: Configure systemd service for Herd-management
      ansible.builtin.copy:
        dest: /etc/systemd/system/herd-management.service
        content: |
          [Unit]
          Description=Herd Management Service
          After=network.target
          StartLimitIntervalSec=0

          [Service]
          Type=simple
          Restart=always
          RestartSec=1
          User=deployment
          WorkingDirectory=/home/deployment/management
          ExecStart=/home/deployment/management/run.sh

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Reload daemon start and enable Herd-management
      ansible.builtin.systemd_service:
        name: herd-management.service
        enabled: true
        state: restarted
        daemon_reload: true
      become: true

## Issue when building in Ansible --> Do this step manually for now
#   - name: Build Herd-agent for backend
#      ansible.builtin.shell: |
#        cd /home/deployment/endpoint
#        sudo ./make.sh install
#      async: 1
#      poll: 0
#      become: true

    - name: Configure systemd service for backend Herd-agent
      ansible.builtin.copy:
        dest: /etc/systemd/system/herd-agent.service
        content: |
          [Unit]
          Description=Herd Endpoint Agent Service
          After=network.target
          StartLimitIntervalSec=0
          
          [Service]
          Type=simple
          Restart=always
          RestartSec=1
          User=root
          WorkingDirectory=/etc/herd
          ExecStart=/usr/bin/herdagent
          
          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Reload daemon start and enable backend Herd-agent
      ansible.builtin.systemd_service:
        name: herd-agent.service
        enabled: true
        state: restarted
        daemon_reload: true
      become: true
